defmodule MyApp.Repo.Migrations.LinkParticipantsToUsers do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:participants) do
      add :user_id,
          references(:users,
            column: :id,
            name: "participants_user_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          )
    end

    alter table(:users) do
      add :hashed_password, :text
    end
  end

  def down do
    alter table(:users) do
      remove :hashed_password
    end

    drop constraint(:participants, "participants_user_id_fkey")

    alter table(:participants) do
      remove :user_id
    end
  end
end
