defmodule MyApp.Repo.Migrations.AddMoreUserAttrs do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      remove :name
      add :given_name, :text, null: false
      add :family_name, :text, null: false
      add :zip_code, :bigint
      add :city, :text
      add :street, :text
      add :phone, :text
      add :language, :text

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end
  end

  def down do
    alter table(:users) do
      remove :updated_at
      remove :created_at
      remove :language
      remove :phone
      remove :street
      remove :city
      remove :zip_code
      remove :family_name
      remove :given_name
      add :name, :text
    end
  end
end
