defmodule MyApp.Repo.Migrations.AddPositions do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:check_ins, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :checked_in_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :checked_out_at, :utc_datetime_usec
      add :participant_id, :uuid, null: false
      add :position_id, :uuid, null: false
    end

    create table(:participants, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:check_ins) do
      modify :participant_id,
             references(:participants,
               column: :id,
               name: "check_ins_participant_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    alter table(:participants) do
      add :session_token, :text, null: false
      add :display_name, :text, null: false
      add :last_seen_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:participants, [:session_token],
             name: "participants_unique_session_token_index"
           )

    create table(:positions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:check_ins) do
      modify :position_id,
             references(:positions,
               column: :id,
               name: "check_ins_position_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    create index(:check_ins, [:participant_id],
             name: "check_ins_one_active_per_participant_index",
             unique: true,
             where: "checked_out_at IS NULL"
           )

    alter table(:positions) do
      add :name, :text, null: false
      add :sort_order, :bigint, null: false, default: 0

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:positions, [:name], name: "positions_unique_name_index")
  end

  def down do
    drop_if_exists unique_index(:positions, [:name], name: "positions_unique_name_index")

    alter table(:positions) do
      remove :updated_at
      remove :inserted_at
      remove :sort_order
      remove :name
    end

    drop_if_exists index(:check_ins, [:participant_id],
                     name: "check_ins_one_active_per_participant_index"
                   )

    drop constraint(:check_ins, "check_ins_position_id_fkey")

    drop constraint(:check_ins, "check_ins_participant_id_fkey")

    alter table(:check_ins) do
      modify :position_id, :uuid
    end

    drop table(:positions)

    drop_if_exists unique_index(:participants, [:session_token],
                     name: "participants_unique_session_token_index"
                   )

    alter table(:participants) do
      remove :updated_at
      remove :inserted_at
      remove :last_seen_at
      remove :display_name
      remove :session_token
    end

    alter table(:check_ins) do
      modify :participant_id, :uuid
    end

    drop table(:participants)

    drop table(:check_ins)
  end
end
